openapi: '3.0.0'
info:
  title: Mouvit App Api
  description: Specification of App Api used by App user
  version: '1.1'
servers:
  - url: http://54.221.108.130:4000
    description: dummy server, for testing purpose
security:
    - Bearer: []
components:
  schemas:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  # ------Login Related Schemas-------#
    OtpRequest: 
      description: request format of generating otp
      properties:
        phone_number:
          description: phone_number of the customer. Number should start with respective country code without prefix "+"
          type: string
          
    OtpVerify: 
      description: request format for verifying otp
      properties:
        phone_number:
          type: string
          description: phone_number of the customer
        otp:
          type: string
          description: otp provided by the customer
    
    CreateCustomer: 
      description: request format of creating customer
      properties:
        phone_number:
          type: string 
          description: phone_number of the customer
        customer_name:
          type: string
          description: name of the customer
        customer_email:
          type: string
          description: email of the customer
        location: 
          type: object
          description: location object holds the two string values lat(Latitude) and long(Longitude), bydefault value can be 0.0 for both lat and long
          properties:
            lat:
              type: number
              description: Latitude
            long:
              type: number
              description: Longitude
        id_proof:
          type: object
          description: holds front and back proof id image path
          properties:
            front:
              type: string
              description: proof id front image path
            back:
              type: string
              description: proof id back image path
            verification_status:
              type: string
              description: verification status, by default value should be not-verified
        stripe_id:
          type: string
          description: to hold the stripe id of the customer. while creating customer stripe_id value is empty.
          
      
    UpdateCustomer: 
      description: request format of updating customer
      properties:
        #--updating profile 
        customer_name:
          type: string
          description: name of the customer
        customer_email:
          type: string
          description: email of the customer
        #--updating location
        location: 
          type: object
          description: location object holds the two numeric values lat(Latitude) and long(Longitude)
          properties:
            lat:
              type: number
              description: Latitude
            long:
              type: number
              description: Longitude
        # updating proof id
        id_proof:
          type: object
          description: holds front and back proof id image path
          properties:
            front:
              type: string
              format: base64 encode
              description: front image base64 string
            back:
              type: string
              format: base64 encode
              description: back image base64 string
            verification_status:
              type: string
              description: verification status, by default value should be not-verified
        #update customer stripe id
        stripe_id:
          type: string
          description: to hold the stripe id of the customer
          
    
    # Response Objects
    #-----Login Related Response Objects---#
    OtpRequestResponse200:
      type: object
      description: otp generated successfully
      properties:
        response_desc:
          type: string
          description: string containes the message "otp sent to provided <phone_number>" 

    
    OtpRequestResponse400:
      type: object
      description: otp generate failed
      properties: 
        response_desc:
          type: string
          description: string containes the message "otp sending failed please try again"
          
        
    OtpVerifyResponse200:
      type: object
      description: otp generated successfully
      properties:
        response_desc:
          type: string
          description: string containes the message "otp verified successfully"
        token: 
          type: string
          description: jwt authentication token
        data:
          type: object 
          description:  will contain customer details
          properties:
            customer_id:
              type: string
              description: customer id created at the time of customer creation. Value will be null if the user is new user
            phone_number:
              type: string
              description: customer phone number
            customer_name:
              type: string
              description: name of the customer. Value will be null if the user is new user
            location: 
              type: object
              description: location object holds the two string values lat(Latitude) and long(Longitude)
              properties:
                lat: 
                  type: number
                  description: latitude value of customer location. Value will be null if the user is new user
                long:
                  type: number
                  description: longitude value of customer location. Value will be null if the user is new user
                  
                  

        
    OtpVerifyResponse400:
      type: object
      description: entered invalid otp 
      properties: 
        response_desc:
          type: string
          description: string containes the message "entered otp is invalid"
          
    
    OtpVerifyResponse410:
      type: object
      description: otp has been expired
      properties:
        response_desc:
          type: string
          description: string containes the message "otp has been expired"
          
    
    CreateCustomerResponse201:
      type: object
      description: customer created successfully
      properties: 
        response_desc:
          type: string
          description: string containes the message "profile created successfully"
        data:
          type: object
          description: object will contain customer_id,customer_name,address,location
          properties: 
            customer_id: 
              type: string
              description: customer id created at the time of customer creation
    
    UpdateCustomerResponse200:
      type: object
      description: customer details updated successfully
      properties: 
        response_desc:
          type: string
          description: string containes the message "profile updated successfully"
        
    UpdateCustomerResponse404:
      type: object
      description: customer details not found
      properties: 
        response_desc:
          type: string
          description: string containes the message "customer details not found"
          
          
    ReadCustomerResponse200:
      type: object
      description: customer details retrieved successfully
      properties:
        response_desc:
          type: string
          description: string containes the message "Operation Successfull"
        data:
          type: object
          description: object containes customer_id,phone_number ,customer_name, customer_email,address,location
          properties:
            phone_number:
              type: string
              description: customer phone number
            customer_name:
              type: string
              description: customer name
            customer_email:
              type: string
              description: customer email
            location:
              type: object
              description: lat and long value of the customer location
              properties:
                lat:
                 type: number
                 description: latitude value of the customer location
                long:
                  type: number
                  description: longitude value of the customer location
            stripe_id:
              type: string
              description: stripe id of the customer
        
          
    ReadCustomerResponse404:
      type: object
      description: customer details not found
      properties: 
        response_desc:
          type: string
          description: string containes the message "customer details not found"
          
    DeleteCustomerResponse200:
      description: deleting the customer profile
      type: object
      properties: 
        response_desc:
          type: string
          description: string containes the message "customer deleted successfully"
        
    
    DeleteCustomerResponse404:
      type: object
      description: customer details not found
      properties: 
        response_desc:
          type: string
          description: string containes the message "customer details not found"
          
    ShowCustomersResponse200:
      type: object
      description: response containing pagination details and search result
      properties:
        response_desc:
          type: string
          description: string containes the message "Operation Successfull"
        pagination:
          type: object
          description: object will contain currentPage, totalRecords perPage
          properties:
            currentPage:
              type: string
              description: current_page number
            totalRecords:
              type: string
              description: total number of records
            perPage:
              type: string
              description: number of records per page  
        data:
          type: object
          description: holds the array customers
          properties:
            customers:
              type: array
              description: holds the search results (customers profile details) in the form of array which holds _id,phone_number,name,email
              items:
                type: object
                properties:
                  customer_id:
                    type: string
                    description: id of the customer
                  phone_number:
                    type: string
                    description: customer phone number
                  customer_name:
                    type: string
                    description: customer name
                  customer_email:
                    type: string
                    description: customer email
                  location:
                    type: object
                    description: containes two decimel value lat and long
                    properties:
                      lat:
                        type: number
                      long:
                        type: number
                  id_proof:
                    type: object
                    description: holds front and back image's path of verification id
                    properties:
                      front:
                        type: string
                        description: front image path of verification id
                      back:
                        type: string
                        description: back image path of verification id
                      verification_status:
                        type: string
                        description: verification status to describe whether customer proof id is verified or not
                  
                      
   
      
      
          
#paths        
paths:
# Login Related Paths---#
  /app/login/action/otprequest:
    #---------Login/Otp related Apis-------#
    post:
      summary: to generate the otp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpRequest'
      responses:
        '200':
          description: otp generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpRequestResponse200'
        
        
        '400':
          description:  otp generate failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpRequestResponse400'

        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
  
 
  /app/login/action/otpverify:
    post:
      summary: to verify the otp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpVerify'
      responses:
        '200':
          description: otp verification successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpVerifyResponse200'
        '400':
          description: otp varification failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpVerifyResponse400'
        '410':
          description: otp Expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpVerifyResponse410'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
  
  /app/login/action/otpresend:
    post:
      summary: to regenerate otp
      security:
        - Bearer: [] 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpRequest'
      responses:
        '200':
          description: otp generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpRequestResponse200'
        '400':
          description: otp generate failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OtpRequestResponse400'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
    
  #-----customer profile---------#
  /app/profile/resource/customer/create:
    post:
      summary: to create new customer profile
      security:
        - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomer'
      responses:
        '201':
          description: customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponse201'
        '400':
          description: customer creation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCustomerResponse400'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
                
  /app/profile/resource/customer/{customer_id}:
    put:
      summary: to updated customer profile
      security:
        - Bearer: []
      parameters:
        - in: path
          name: customer_id
          schema:
            type: string
          required: true
          description: unique string to identify customer details
            
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomer'
      responses:
        '200':
          description: customer details updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerResponse200'
        '404':
          description: customer details not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerResponse404'
        '400':
          description: customer updation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateCustomerResponse400'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
        
        
    
    get:
      summary: read customer profile details
      security:
        - Bearer: []
      parameters:
        - in: path
          name: customer_id
          schema:
            type: string
          required: true
          description: unique string to identify customer details
          
      responses:
        '200':
          description: customer details read successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadCustomerResponse200'
        '404':
          description: customer details not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadCustomerResponse404'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
    
    
    delete:
      summary: delete customer profile
      security:
        - Bearer: []
      parameters:
        - in: path
          name: customer_id
          schema:
            type: string
          required: true
          description: unique string to identify customer details
      responses:
        '200':
          description: customer details deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCustomerResponse200'
        '404':
          description: customer details not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteCustomerResponse404'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'
  
  /mouvit/customers/show:
    get:
      summary: admin request to get the list of customers
      security:
        - Bearer: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            description: page number 
        - in: query
          name: limit
          schema:
            type: integer
            description: items limit for the page
        - in: query
          name: search
          schema:
            type: string
            description: search string
      responses:
        '200':
            description: customers profile found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ShowCustomersResponse200'
        '500':
          description:  internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse500'


  
      


      