version: 2.1 
 
# Define the jobs we want to run for this project
orbs:    
  newman: postman/newman@0.0.2  
  aws-cli: circleci/aws-cli@2.0
   
jobs: 
  start-ec2:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: kiikie 
          aws-region: kkiio 
          aws-secret-access-key: kiiikke 
          configure-default-region: false 
          profile-name: example 
          role-arn: eeeeeeee
      - run: "aws ec2 start-instances --instance-ids i-1234567890abcdef"
  # start-ec2:
  #   docker:
  #     - image: cimg/base:stable
  #   executor: aws-cli/default
  #   steps:
  # #     # - aws-cli/setup
  # #     # - aws-cli/install 
  #       - run: aws ec2 start-instances --instance-ids i-1234567890abcdef0
  
  #Deployment Command
  # pull-and-build:  
  #   docker:  
  #     - image: arvindr226/alpine-ssh 
  #   steps:  
  #     - run: apk add --update openssh-client git
  #     - checkout
  #     - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
  #     - run: 
  #         command: |
  #           'send deployment failuer status revert changes'
  #         when: on_fail

  # newman-collection-run:
  #   executor: newman/postman-newman-docker
  #   steps:
  #     - checkout
  #     - newman/newman-run:
  #         collection: https://www.getpostman.com/collections/6446f5ecd440f49e4746?apikey=PMAK-61934b34bd1cd60051615fc3-a40f33edd7df44f1e7bf05b1fedefe47b7 
  #     - run: 
  #         command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./revertdeploy.sh"
  #         when: on_fail 

  # #deploy to the test server
  # deploy:
  #   docker:
  #     - image: arvindr226/alpine-ssh
  #   steps:
  #     #ip and user of the test server
  #     - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploytest.sh"

  newman-collection-run-test:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://www.getpostman.com/collections/6446f5ecd440f49e4746?apikey=PMAK-61934b34bd1cd60051615fc3-a40f33edd7df44f1e7bf05b1fedefe47b7 
      - run: 
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./revertdeploy.sh"
          when: on_fail

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - start-ec2
      # - pull-and-build:
      #     filters:
      #       branches:
      #         only:
      #           - master
                
      # - newman-collection-run: 
      #     requires:
      #       - pull-and-build
          
      # - deploy:
      #     requires:
      #       - newman-collection-run
      
      # - newman-collection-run-test:
      #     requires:
      #       - deploy