version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            "ssh ubuntu@54.221.108.130 sudo rm ~/iotracx/swaggertest/AppAPIs.yaml"
